version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sass
    versions:
    - 1.32.11
    - 1.32.5
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: ember-power-select
    versions:
    - 4.1.0
    - 4.1.2
    - 4.1.3
  - dependency-name: ember-changeset-validations
    versions:
    - 3.10.3
    - 3.11.0
    - 3.12.0
    - 3.13.0
    - 3.14.1
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
  - dependency-name: eslint
    versions:
    - 7.7.0
  - dependency-name: jquery
    versions:
    - 3.5.1
