---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  firefox: latest
  chrome: stable

cache:
  directories:
    - $HOME/.npm
    - node_modules
    - bower_components

before_install:
  - npm install -g npm@5
  - npm install -g bower

install:
  - npm install
  - bower install

script:
  - COVERAGE=true npm test

after_script:
  - cat coverage/lcov.info | coveralls
