---
language: node_js
node_js:
  - "8"

addons:
  firefox: latest
  chrome: stable

cache:
  yarn: true

install:
  - yarn

script:
  - yarn test

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  - COVERAGE=true JOBS=2
